// Package suspect finds a value that no classification rule recognised and
// that still does not read like a setting.
//
// The classifier opens a value it does not recognise. That is deliberate: a
// tool that veils every unknown value hides the log level and the time zone,
// and a tool that does that gets switched off. But an opened value that nobody
// looked at is exactly how a credential reaches an agent, and today the tool
// prints "open" and the developer has no reason to look again.
//
// So this package makes the unknown visible instead of veiling it. It never
// changes the class of a value. It only says that a person should read this
// row, and why.
//
// It is built for recall and not for precision. A wrong guess here costs one
// line of output that a person reads once. A missed guess costs a credential
// that nobody ever reads. The two costs are not equal, so the tests are.
package suspect

import (
	"strings"

	"github.com/ByteFinch-Technologies/secretveil/internal/shape"
)

// minTokenLen is the shortest value that is worth a second look.
//
// It is below the 20 characters that the entropy rule needs, because this
// package reports and does not veil, so it can afford to look further down.
const minTokenLen = 12

// longTokenLen is the length at which a value with no words in it is worth
// reporting whatever else it holds.
const longTokenLen = 20

// vendorStarts are the openings of a credential that a vendor issues.
//
// A value that starts this way and that reached this package has failed its
// own shape rule, which almost always means it is shorter than the vendor
// issues. That is worth saying out loud: the value is either a credential that
// the tool must learn, or a placeholder that somebody left in the file.
var vendorStarts = strings.Fields(`
	sk- sk_live_ sk_test_ rk_live_ rk_test_ pk_live_ npm_ xox ghp_ gho_ ghu_
	ghs_ ghr_ github_pat_ glpat- glptt- AKIA ASIA AIza SG. SK shp sq0 key-
	eyJ -----BEGIN
`)

// Reason says why a value is worth a second look, or returns an empty string.
//
// The key is read as well as the value. A name the tool already understood
// would have been decided by a rule before this package ran, so a name here
// tells us nothing on its own. It is used only to keep the message readable.
func Reason(key, value string) string {
	v := strings.TrimSpace(value)
	if v == "" {
		return ""
	}
	for _, start := range vendorStarts {
		if strings.HasPrefix(v, start) {
			return "the value starts like a credential that a vendor issues"
		}
	}
	if len(v) < minTokenLen {
		return ""
	}
	// A value with a space in it is a sentence, a list or a command line.
	if strings.ContainsAny(v, " \t") {
		return ""
	}
	// An address is what the agent is meant to read.
	if strings.Contains(v, "://") {
		return ""
	}
	if _, ok := shape.Alphabet(v); !ok {
		return ""
	}
	// A name that a person wrote reaches this length easily, and the shape
	// package already knows how to read one.
	if !shape.LooksRandom(v) && looksWritten(v) {
		return ""
	}
	if len(v) >= longTokenLen {
		return "the value is long and holds no word"
	}
	if mixedCaseWithDigits(v) {
		return "the value mixes both letter cases with digits"
	}
	return ""
}

// looksWritten reports whether a value reads as something a person typed.
//
// The shape package refuses a name and a path before it veils, so a value that
// it refuses for that reason is not reported here either. The test is the
// same one, asked through the public rule: a value that is long enough to be a
// token and that the rule still leaves open is a name, a path or a repeat.
func looksWritten(value string) bool {
	return len(value) >= longTokenLen
}

// mixedCaseWithDigits reports whether a value holds a lower case letter, an
// upper case letter and a digit. A setting rarely does all three. A key that
// somebody generated by hand almost always does.
func mixedCaseWithDigits(value string) bool {
	var lower, upper, digit bool
	for i := 0; i < len(value); i++ {
		switch c := value[i]; {
		case c >= 'a' && c <= 'z':
			lower = true
		case c >= 'A' && c <= 'Z':
			upper = true
		case c >= '0' && c <= '9':
			digit = true
		}
	}
	return lower && upper && digit
}
