// Package corpus builds the labelled set of values that the classifier tests
// measure against.
//
// Every value here is made by this code from a fixed seed. No value is typed
// in by hand, and no value came from a real system.
//
// The rows are never written to a file of this repository. Each one has the
// shape of a real credential, because a value that does not look like a
// credential measures nothing, and a file of such values is wrong in a public
// repository: the host refuses the push, and a reader cannot tell a made-up
// key from a real one. TestNoCorpusValueIsStoredInTheRepository holds that
// line by reading every file of the tree.
//
// The package is imported by the classifier tests and by the adversarial test
// that runs a real init over the whole set. No command imports it, and
// test/nonetwork fails if one ever does.
package corpus

import (
	"fmt"
	"math/rand"
	"sort"
	"strings"
)

// Seed fixes the generator. Change it and every value changes, so do not
// change it without a reason.
const Seed = 20260819

// Want says what the classifier must do with a row.
type Want string

const (
	// Secret means no part named in Sensitive may survive into the file the
	// agent reads.
	Secret Want = "secret"
	// Open means the value must reach the agent in full.
	Open Want = "open"
)

// Row is one labelled example.
type Row struct {
	Key   string
	Value string
	Want  Want
	// Sensitive lists the parts of Value that must not survive. It holds one
	// entry for a whole secret and one entry per field for a composite. It is
	// empty for an open row.
	Sensitive []string
	// Note says why the row is labelled the way it is. It is for the human who
	// reads the file, and no test reads it.
	Note string
}

// Generate returns the whole corpus, in a stable order.
func Generate() []Row {
	g := &gen{r: rand.New(rand.NewSource(Seed))}
	var rows []Row
	rows = append(rows, g.namedSecrets()...)
	rows = append(rows, g.vendorShapes()...)
	rows = append(rows, g.blandRandom()...)
	rows = append(rows, g.composites()...)
	rows = append(rows, g.configNames()...)
	rows = append(rows, g.publicPrefixes()...)
	rows = append(rows, g.plainValues()...)
	for i, row := range rows {
		if err := row.check(); err != nil {
			panic(fmt.Sprintf("corpus row %d (%s): %v", i, row.Key, err))
		}
	}
	return rows
}

// check refuses a row that would break the file format or the labelling.
func (r Row) check() error {
	for _, s := range []string{r.Key, r.Value, r.Note} {
		if strings.ContainsAny(s, "\t\n\r") {
			return fmt.Errorf("a tab or a newline is not allowed")
		}
	}
	switch r.Want {
	case Secret:
		if len(r.Sensitive) == 0 {
			return fmt.Errorf("a secret row must name what is sensitive")
		}
		for _, s := range r.Sensitive {
			if s == "" || strings.Contains(s, " ") {
				return fmt.Errorf("a sensitive part must not be empty or hold a space")
			}
			if !strings.Contains(r.Value, s) {
				return fmt.Errorf("the sensitive part %q is not in the value", s)
			}
		}
	case Open:
		if len(r.Sensitive) != 0 {
			return fmt.Errorf("an open row must name nothing sensitive")
		}
	default:
		return fmt.Errorf("the want %q is not known", r.Want)
	}
	return nil
}

// ------------------------------------------------------------------ reading

// Marshal renders the corpus as tab separated text.
//
// Nothing writes the result to a file. Two tests compare two calls to prove
// the generator is stable, and a developer can print it to read the rows.
func Marshal(rows []Row) string {
	var b strings.Builder
	b.WriteString("# The labelled corpus for the secret classifier.\n")
	b.WriteString("# Every value is generated by internal/corpus from a fixed seed.\n")
	b.WriteString("# Do not edit this file. Change internal/corpus and run:\n")
	b.WriteString("#   go test ./internal/classify -run TestEveryCorpusValueIsGenerated -update\n")
	b.WriteString("#\n")
	b.WriteString("# key\tvalue\twant\tsensitive\tnote\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "%s\t%s\t%s\t%s\t%s\n",
			r.Key, r.Value, r.Want, strings.Join(r.Sensitive, " "), r.Note)
	}
	return b.String()
}

// ------------------------------------------------------------- the values

type gen struct{ r *rand.Rand }

const (
	hexDigits    = "0123456789abcdef"
	alnumDigits  = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
	base64Digits = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
	upperDigits  = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
)

func (g *gen) pick(alphabet string, n int) string {
	b := make([]byte, n)
	for i := range b {
		b[i] = alphabet[g.r.Intn(len(alphabet))]
	}
	return string(b)
}

func (g *gen) hex(n int) string    { return g.pick(hexDigits, n) }
func (g *gen) alnum(n int) string  { return g.pick(alnumDigits, n) }
func (g *gen) base64(n int) string { return g.pick(base64Digits, n) }

// weak returns a short password that no entropy rule can catch. Only the name
// of the variable can save a value like this, which is what makes it the sharp
// test of the name rules.
func (g *gen) weak(i int) string {
	words := []string{"Hunter2!", "letmein", "changeme", "Passw0rd", "admin123", "s3cret", "qwerty1", "P@ssw0rd1"}
	return words[i%len(words)]
}

// ------------------------------------------------------- named secrets

// secretKeys holds variable names that name a credential. Every one of these
// was seen in a real project, in a public example or in a vendor document. The
// name alone must be enough, so each is paired with a weak value as well as a
// random one.
var secretKeys = []string{
	// Passwords, including the names that a substring rule gets wrong.
	"ADMIN_PASSWORD", "KEYCLOAK_ADMIN_PASSWORD", "GRAFANA_ADMIN_PASSWORD",
	"WINDOWS_PASSWORD", "MAX_PASSWORD", "MIN_PASSWORD", "DB_PASSWORD",
	"POSTGRES_PASSWORD", "MYSQL_ROOT_PASSWORD", "REDIS_PASSWORD",
	"MONGO_INITDB_ROOT_PASSWORD", "SUDO_PASSWORD", "VNC_PASSWORD",
	"ROOT_PASSWORD", "SMTP_PASSWORD", "LDAP_BIND_PASSWORD",
	// The PASS spelling, which no rule covers today.
	"SMTP_PASS", "DB_PASS", "MYSQL_PASS", "POSTGRES_PASS", "REDIS_PASS",
	"MONGO_PASS", "FTP_PASS", "KEYSTORE_PASS", "TRUSTSTORE_PASS",
	"PROXY_PASS", "BASIC_AUTH_PASS", "RABBITMQ_DEFAULT_PASS",
	// Keys, including the names that ACCOUNT and MIN break.
	"ALGOLIA_ADMIN_KEY", "GCP_SERVICE_ACCOUNT_KEY", "AZURE_STORAGE_ACCOUNT_KEY",
	"AWS_SECRET_ACCESS_KEY", "STRIPE_SECRET_KEY", "SENDGRID_API_KEY",
	"MAILGUN_API_KEY", "DEEPGRAM_API_KEY", "ENCRYPTION_KEY", "MASTER_KEY",
	"SIGNING_KEY", "JWT_PRIVATE_KEY", "SSH_PRIVATE_KEY", "APPLE_PRIVATE_KEY",
	"WEBHOOK_SIGNING_KEY", "PAYFAST_MERCHANT_KEY", "COUNTRY_API_KEY",
	"ACCOUNT_SECRET_KEY", "MINIO_SECRET_KEY", "MINIO_ROOT_PASSWORD",
	// Tokens, including the names that DEBUG, VERSION and REGION break.
	"DEBUG_TOKEN", "VERSION_SECRET", "REGION_SECRET", "MODE_SECRET",
	"GITHUB_TOKEN", "GITLAB_TOKEN", "NPM_TOKEN", "SLACK_BOT_TOKEN",
	"DISCORD_BOT_TOKEN", "VERCEL_TOKEN", "CLOUDFLARE_API_TOKEN",
	"DATADOG_APP_KEY", "PAGERDUTY_TOKEN", "SENTRY_AUTH_TOKEN",
	"REFRESH_TOKEN", "ACCESS_TOKEN", "SESSION_TOKEN", "TWILIO_AUTH_TOKEN",
	"HUGGINGFACE_TOKEN", "COUNT_TOKEN", "WINDOW_TOKEN",
	// Words that no rule holds today.
	"DB_CREDS", "AWS_CREDS", "WALLET_MNEMONIC", "SEED_PHRASE",
	"RECOVERY_PHRASE", "HMAC_KEY", "WEBHOOK_HMAC", "TOTP_SEED",
	"ENCRYPTION_IV", "REQUEST_SIGNATURE", "BEARER_TOKEN", "GITHUB_PAT",
	"AZURE_SAS", "AZURE_SAS_TOKEN", "SUPABASE_SERVICE_ROLE",
	"SUPABASE_SERVICE_ROLE_KEY", "DATABASE_CONNECTION_STRING",
	"STORAGE_CONNECTION_STRING", "NONCE_SECRET", "SLACK_WEBHOOK",
	"DISCORD_WEBHOOK", "TEAMS_WEBHOOK", "SESSION_PASSPHRASE",
	"CLIENT_CERTIFICATE", "PFX_PASSWORD", "COOKIE_SECRET", "CSRF_SECRET",
	// Camel case and other separators, which a split on the underscore alone
	// would miss.
	"stripeSecretKey", "databasePassword", "github-token", "smtp.password",
	"AUTH0_CLIENT_SECRET", "OKTA_API_TOKEN", "SEGMENT_WRITE_KEY",
}

func (g *gen) namedSecrets() []Row {
	var rows []Row
	for i, k := range secretKeys {
		// Three weak values. Only the name can decide these.
		for j := 0; j < 3; j++ {
			v := g.weak(i + j)
			rows = append(rows, Row{Key: k, Value: v, Want: Secret,
				Sensitive: []string{v}, Note: "the name says secret and the value is weak"})
		}
		// Two random values. The name and the value both point one way.
		for _, v := range []string{g.hex(32), g.alnum(40)} {
			rows = append(rows, Row{Key: k, Value: v, Want: Secret,
				Sensitive: []string{v}, Note: "the name says secret and the value is random"})
		}
	}
	return rows
}

// --------------------------------------------------------- vendor shapes

// vendorShapes pairs a bland variable name with a value that a vendor stamps
// with a recognisable prefix. The name says nothing, so only the value rule can
// save these.
func (g *gen) vendorShapes() []Row {
	blandNames := []string{"SETTING", "CONFIG_VALUE", "APP_DATA", "PARAM", "OPTION", "ITEM"}
	// Each maker returns the whole value and the part that must not survive.
	// For a key block the part is the key material, because the header is
	// public and holds a space, which the file format does not carry.
	makers := []struct {
		name string
		make func() (value, sensitive string)
	}{
		{"aws-access-key-id", func() (string, string) { v := "AKIA" + g.pick(upperDigits, 16); return v, v }},
		{"aws-temp-key-id", func() (string, string) { v := "ASIA" + g.pick(upperDigits, 16); return v, v }},
		{"openai-key", func() (string, string) { v := "sk-" + g.alnum(48); return v, v }},
		{"openai-project-key", func() (string, string) { v := "sk-proj-" + g.alnum(64); return v, v }},
		{"stripe-live-key", func() (string, string) { v := "sk_live_" + g.alnum(24); return v, v }},
		{"stripe-test-key", func() (string, string) { v := "sk_test_" + g.alnum(24); return v, v }},
		{"stripe-restricted-key", func() (string, string) { v := "rk_live_" + g.alnum(24); return v, v }},
		{"github-classic", func() (string, string) { v := "ghp_" + g.alnum(36); return v, v }},
		{"github-oauth", func() (string, string) { v := "gho_" + g.alnum(36); return v, v }},
		{"github-user", func() (string, string) { v := "ghu_" + g.alnum(36); return v, v }},
		{"github-server", func() (string, string) { v := "ghs_" + g.alnum(36); return v, v }},
		{"github-refresh", func() (string, string) { v := "ghr_" + g.alnum(36); return v, v }},
		{"gitlab-token", func() (string, string) { v := "glpat-" + g.alnum(20); return v, v }},
		{"npm-token", func() (string, string) { v := "npm_" + g.alnum(36); return v, v }},
		{"npm-token-long", func() (string, string) { v := "npm_" + g.alnum(40); return v, v }},
		{"slack-bot", func() (string, string) {
			v := "xoxb-" + g.pick("0123456789", 13) + "-" + g.alnum(24)
			return v, v
		}},
		{"slack-user", func() (string, string) {
			v := "xoxp-" + g.pick("0123456789", 13) + "-" + g.alnum(24)
			return v, v
		}},
		{"google-api-key", func() (string, string) { v := "AIza" + g.pick(alnumDigits+"-_", 35); return v, v }},
		{"jwt", func() (string, string) {
			v := "eyJ" + g.pick(alnumDigits+"-_", 22) + "." + g.pick(alnumDigits+"-_", 40) + "." + g.pick(alnumDigits+"-_", 43)
			return v, v
		}},
		{"sendgrid", func() (string, string) {
			v := "SG." + g.pick(alnumDigits+"-_", 22) + "." + g.pick(alnumDigits+"-_", 43)
			return v, v
		}},
		{"twilio-signing-key", func() (string, string) { v := "SK" + g.hex(32); return v, v }},
		{"square-token", func() (string, string) { v := "sq0atp-" + g.pick(alnumDigits+"-_", 22); return v, v }},
		{"rsa-private-key", func() (string, string) {
			b := g.base64(40)
			return "-----BEGIN RSA PRIVATE KEY-----" + b, b
		}},
		{"openssh-private-key", func() (string, string) {
			b := g.base64(40)
			return "-----BEGIN OPENSSH PRIVATE KEY-----" + b, b
		}},
		{"ec-private-key", func() (string, string) {
			b := g.base64(40)
			return "-----BEGIN EC PRIVATE KEY-----" + b, b
		}},
		{"pgp-private-key", func() (string, string) {
			b := g.base64(40)
			return "-----BEGIN PGP PRIVATE KEY BLOCK-----" + b, b
		}},
	}
	var rows []Row
	for i, m := range makers {
		for j := 0; j < 3; j++ {
			v, sens := m.make()
			rows = append(rows, Row{
				Key: blandNames[(i+j)%len(blandNames)], Value: v, Want: Secret,
				Sensitive: []string{sens}, Note: "the value carries the " + m.name + " shape",
			})
		}
	}
	return rows
}

// ----------------------------------------------------------- bland random

// blandRandom is the hardest set. The name says nothing and the value carries
// no vendor prefix, so only the entropy rule can save these. Short lengths are
// where the measurement showed the rule failing.
func (g *gen) blandRandom() []Row {
	names := []string{"ACME_BLURB", "SETTING", "OPTION_A", "WIDGET", "THING", "PARAM"}
	kinds := []struct {
		name string
		make func(int) string
	}{
		{"hex", g.hex},
		{"alnum", g.alnum},
		{"base64", g.base64},
	}
	var rows []Row
	for _, n := range []int{24, 32, 40, 48, 64} {
		for _, k := range kinds {
			for i := 0; i < 4; i++ {
				v := k.make(n)
				rows = append(rows, Row{
					Key: names[(n+i)%len(names)], Value: v, Want: Secret,
					Sensitive: []string{v},
					Note:      fmt.Sprintf("a random %s token of %d characters under a name that says nothing", k.name, n),
				})
			}
		}
	}
	return rows
}

// ------------------------------------------------------------ composites

// composites hold a readable part and a secret part. The readable part must
// survive, because the agent needs it, and the secret part must not.
func (g *gen) composites() []Row {
	var rows []Row
	for i := 0; i < 4; i++ {
		pw := g.alnum(16)
		v := fmt.Sprintf("postgres://appuser:%s@db%d.internal:5432/appdb", pw, i)
		rows = append(rows, Row{Key: "DATABASE_URL", Value: v, Want: Secret,
			Sensitive: []string{pw}, Note: "a url that carries a password"})
	}
	for i := 0; i < 3; i++ {
		pw := g.alnum(14)
		v := fmt.Sprintf("mongodb+srv://svc:%s@cluster%d.mongodb.net/app", pw, i)
		rows = append(rows, Row{Key: "MONGO_URI", Value: v, Want: Secret,
			Sensitive: []string{pw}, Note: "a url that carries a password"})
	}
	for i := 0; i < 3; i++ {
		tok := g.alnum(24)
		v := fmt.Sprintf("https://api.example.com/v%d/feed?format=json&token=%s", i+1, tok)
		rows = append(rows, Row{Key: "FEED_URL", Value: v, Want: Secret,
			Sensitive: []string{tok}, Note: "a url that carries a token in the query"})
	}
	// Both at once. One field veiled and the other left in the clear is the
	// failure this set exists to catch.
	for i := 0; i < 3; i++ {
		pw, tok := g.alnum(14), g.alnum(22)
		v := fmt.Sprintf("https://svcuser:%s@gateway%d.example.com/pull?api_key=%s", pw, i, tok)
		rows = append(rows, Row{Key: "GATEWAY_URL", Value: v, Want: Secret,
			Sensitive: []string{pw, tok}, Note: "a url that carries a password and a token"})
	}
	for i := 0; i < 3; i++ {
		pw := g.alnum(18)
		v := fmt.Sprintf("Server=tcp:sql%d.database.windows.net,1433;Database=app;User ID=svc;Password=%s;Encrypt=true", i, pw)
		rows = append(rows, Row{Key: "SQL_CONNECTION", Value: v, Want: Secret,
			Sensitive: []string{pw}, Note: "a connection string that carries a password"})
	}
	for i := 0; i < 3; i++ {
		tok := g.alnum(32)
		rows = append(rows, Row{Key: "UPSTREAM_AUTH", Value: "Bearer " + tok, Want: Secret,
			Sensitive: []string{tok}, Note: "an authorization header value"})
	}
	// A query credential list long enough to reach the tenth parameter, which
	// is where the reference naming breaks.
	var parts []string
	var sens []string
	names := []string{"token", "key", "api_key", "apikey", "password", "secret", "sig", "signature", "access_token", "auth"}
	for _, n := range names {
		t := g.alnum(18)
		parts = append(parts, n+"="+t)
		sens = append(sens, t)
	}
	rows = append(rows, Row{
		Key: "MULTI_URL", Value: "https://api.example.com/x?" + strings.Join(parts, "&"),
		Want: Secret, Sensitive: sens, Note: "ten credentials in one query, which is where the reference naming breaks",
	})
	return rows
}

// ----------------------------------------------------------- config names

// configTerm pairs a variable name with values that are true configuration.
// Veiling one of these costs the agent information and protects nothing.
type configTerm struct {
	key    string
	values []string
}

var configTerms = []configTerm{
	{"PORT", []string{"3000", "8080", "5432", "443"}},
	{"DB_PORT", []string{"5432", "3306", "27017", "6379"}},
	{"NODE_ENV", []string{"production", "development", "test", "staging"}},
	{"ENV", []string{"production", "dev", "qa", "local"}},
	{"APP_ENV", []string{"production", "sandbox", "ci", "preview"}},
	{"LOG_LEVEL", []string{"debug", "info", "warn", "error"}},
	{"LOG_FORMAT", []string{"json", "text", "pretty", "logfmt"}},
	{"AWS_REGION", []string{"us-east-1", "eu-central-1", "ap-south-1", "me-central-1"}},
	{"AWS_DEFAULT_REGION", []string{"us-west-2", "eu-west-1", "sa-east-1", "af-south-1"}},
	{"GCP_ZONE", []string{"us-central1-a", "europe-west4-b", "asia-south1-c", "me-west1-a"}},
	{"MAX_RETRIES", []string{"3", "5", "10", "0"}},
	{"RETRY_COUNT", []string{"2", "4", "6", "8"}},
	{"RETRY_DELAY_MS", []string{"250", "500", "1000", "2000"}},
	{"CACHE_TTL", []string{"60", "300", "3600", "86400"}},
	{"REFRESH_TOKEN_TTL_DAYS", []string{"7", "14", "30", "90"}},
	{"ACCESS_TOKEN_TTL_SECONDS", []string{"300", "900", "1800", "3600"}},
	{"SESSION_TIMEOUT", []string{"1800", "3600", "7200", "600"}},
	{"REQUEST_TIMEOUT_MS", []string{"5000", "10000", "30000", "1500"}},
	{"CONNECT_TIMEOUT", []string{"5", "10", "30", "60"}},
	{"PAGE_SIZE", []string{"20", "50", "100", "25"}},
	{"PER_PAGE", []string{"10", "25", "50", "100"}},
	{"MAX_CONNECTIONS", []string{"10", "20", "50", "100"}},
	{"MIN_POOL_SIZE", []string{"1", "2", "5", "10"}},
	{"MAX_POOL_SIZE", []string{"10", "25", "50", "80"}},
	{"MAX_UPLOAD_SIZE", []string{"5242880", "10485760", "1048576", "20971520"}},
	{"BCRYPT_ROUNDS", []string{"10", "12", "14", "8"}},
	{"LOGIN_ATTEMPTS", []string{"3", "5", "10", "6"}},
	{"RATE_LIMIT", []string{"100", "1000", "60", "500"}},
	{"RATE_LIMIT_WINDOW", []string{"60", "300", "900", "3600"}},
	{"ALERT_THRESHOLD", []string{"80", "90", "95", "70"}},
	{"WORKER_COUNT", []string{"1", "4", "8", "16"}},
	{"CONCURRENCY", []string{"2", "4", "8", "32"}},
	{"REPLICAS", []string{"1", "2", "3", "5"}},
	{"DEBUG", []string{"true", "false", "0", "1"}},
	{"VERBOSE", []string{"true", "false", "yes", "no"}},
	{"CACHE_ENABLED", []string{"true", "false", "on", "off"}},
	{"TELEMETRY_DISABLED", []string{"true", "false", "1", "0"}},
	{"STRICT_MODE", []string{"true", "false", "on", "off"}},
	{"DRY_RUN", []string{"true", "false", "yes", "no"}},
	{"APP_VERSION", []string{"1.0.0", "2.14.3", "v3.0.0-rc1", "0.1.0"}},
	{"API_VERSION", []string{"v1", "v2", "2024-06-01", "3"}},
	{"SCHEMA_VERSION", []string{"1", "12", "2.1", "7"}},
	{"BUILD_NUMBER", []string{"142", "9981", "3", "20260819"}},
	{"RELEASE_TAG", []string{"v1.2.3", "v0.9.0", "v10.0.0-beta", "v2.0.1"}},
	{"TZ", []string{"UTC", "Asia/Karachi", "Europe/Berlin", "Asia/Dubai"}},
	{"TIMEZONE", []string{"UTC", "Asia/Dubai", "America/New_York", "Europe/London"}},
	{"LOCALE", []string{"en_US", "de_DE", "ur_PK", "ar_AE"}},
	{"LANG", []string{"en", "de", "ur", "ar"}},
	{"DEFAULT_CURRENCY", []string{"USD", "EUR", "PKR", "AED"}},
	{"LOG_PATH", []string{"/var/log/app.log", "./logs/out.log", "/tmp/app/debug.log", "logs/app.log"}},
	{"DATA_DIR", []string{"/var/lib/app", "./data", "/srv/app/data", "data/store"}},
	{"UPLOAD_FOLDER", []string{"/var/uploads", "./public/uploads", "/srv/files", "uploads/tmp"}},
	{"CONFIG_FILE", []string{"/etc/app/config.yaml", "./config.json", "/opt/app/app.toml", "config/dev.yaml"}},
	{"DB_PASSWORD_FILE", []string{"/run/secrets/db_password", "/var/run/secrets/pg", "./secrets/db.txt", "/etc/app/db.pass"}},
	{"TLS_CERT_PATH", []string{"/etc/ssl/certs/app.pem", "./certs/server.crt", "/opt/tls/full.pem", "certs/chain.pem"}},
	{"SSH_KEY_PATH", []string{"/home/deploy/.ssh/id_rsa", "./keys/deploy", "/etc/ssh/deploy_key", "keys/ci_ed25519"}},
	{"DB_HOST", []string{"localhost", "db.internal", "postgres.default.svc", "127.0.0.1"}},
	{"REDIS_HOST", []string{"redis", "cache.internal", "10.0.1.24", "redis.default.svc"}},
	{"API_HOSTNAME", []string{"api.example.com", "api.staging.example.com", "localhost", "gateway.internal"}},
	{"APP_DOMAIN", []string{"example.com", "app.example.com", "bytefinch.dev", "staging.example.org"}},
	{"API_BASE_URL", []string{"https://api.example.com", "http://localhost:3000", "https://staging.example.com/v2", "https://eu.example.com"}},
	{"CALLBACK_URL", []string{"https://app.example.com/callback", "http://localhost:3000/auth", "https://example.com/oauth/done", "https://x.example.com/cb"}},
	{"HEALTHCHECK_ENDPOINT", []string{"/healthz", "/health", "/-/ready", "/status"}},
	{"S3_BUCKET", []string{"app-uploads", "prod-assets-eu", "backups-2026", "media-store"}},
	{"KAFKA_TOPIC", []string{"orders", "user-events", "payments-dlq", "audit-log"}},
	{"QUEUE_NAME", []string{"default", "emails", "high-priority", "reports"}},
	{"K8S_NAMESPACE", []string{"default", "production", "staging", "app-system"}},
	{"DB_DRIVER", []string{"postgres", "mysql", "sqlite", "mssql"}},
	{"CACHE_PROVIDER", []string{"redis", "memory", "memcached", "none"}},
	{"MAIL_TRANSPORT", []string{"smtp", "ses", "sendgrid", "log"}},
	{"STORAGE_ADAPTER", []string{"s3", "local", "gcs", "azure"}},
	{"AUTH_STRATEGY", []string{"oidc", "saml", "local", "ldap"}},
	{"JWT_ALGORITHM", []string{"HS256", "RS256", "ES256", "EdDSA"}},
	{"HASH_ALGO", []string{"sha256", "sha512", "blake2b", "argon2id"}},
	{"TOKEN_TYPE", []string{"Bearer", "Basic", "MAC", "DPoP"}},
	{"CONTENT_TYPE", []string{"application/json", "text/plain", "application/xml", "text/csv"}},
	{"AUTH_HEADER_NAME", []string{"Authorization", "X-Api-Key", "X-Auth-Token", "Proxy-Authorization"}},
	{"CACHE_KEY_PREFIX", []string{"app", "prod:v2", "svc-cache", "session"}},
	{"TABLE_PREFIX", []string{"wp_", "app_", "prod_", "core_"}},
	{"FILE_SUFFIX", []string{".bak", ".tmp", ".old", ".gz"}},
	{"JWT_ISSUER", []string{"https://auth.example.com", "example-app", "https://login.example.org", "svc-issuer"}},
	{"JWT_AUDIENCE", []string{"api.example.com", "mobile-app", "https://api.example.org", "internal"}},
	{"DB_USER", []string{"postgres", "appuser", "readonly", "svc_app"}},
	{"DB_USERNAME", []string{"admin", "app", "reporting", "migrator"}},
	{"SMTP_USER", []string{"apikey", "noreply@example.com", "mailer", "svc-smtp"}},
	{"AWS_ACCESS_KEY_ID_NAME", []string{"deploy-key", "ci-runner", "backup-agent", "reporter"}},
	{"SERVICE_NAME", []string{"payments-api", "web", "worker", "scheduler"}},
	{"APP_NAME", []string{"ByteFinch", "checkout", "admin-portal", "gateway"}},
	{"CLIENT_ID", []string{"0oa1b2c3d4e5f6g7h8i9", "my-app-client", "1234567890-abc.apps.googleusercontent.com", "svc-web"}},
	{"TENANT_ID", []string{"contoso", "acme-eu", "default", "tenant-42"}},
	{"PROJECT_ID", []string{"my-gcp-project", "app-prod-1234", "bytefinch-dev", "sandbox-9"}},
	{"GIT_COMMIT_SHA", []string{"9c79fb5", "a9cd452b1e", "0205e82f3c4d5e6a7b8c9d0e1f2a3b4c5d6e7f80", "317ec6b"}},
	{"GIT_BRANCH", []string{"main", "develop", "release/1.2", "feature/login"}},
	{"BUILD_REVISION", []string{"deadbeef", "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b", "abc1234", "0f0f0f0"}},
	{"ASSET_CHECKSUM", []string{"d41d8cd98f00b204e9800998ecf8427e", "5d41402abc4b2a76b9719d911017c592", "aaf4c61d", "e3b0c44298fc1c14"}},
	{"NEXT_TELEMETRY_DISABLED", []string{"1", "0", "true", "false"}},
	{"CI", []string{"true", "false", "1", "0"}},
	{"COLOR_SCHEME", []string{"dark", "light", "auto", "high-contrast"}},
	{"UI_THEME", []string{"default", "compact", "corporate", "night"}},
	{"FEATURE_FLAG_MODE", []string{"local", "remote", "hybrid", "off"}},
	{"SORT_ORDER", []string{"asc", "desc", "created_at", "-updated_at"}},
	{"DEFAULT_ROLE", []string{"viewer", "editor", "admin", "guest"}},
	{"HTTP_PROTOCOL", []string{"http", "https", "h2", "h3"}},
	{"REQUEST_METHOD", []string{"GET", "POST", "PUT", "PATCH"}},
	{"OUTPUT_FORMAT", []string{"json", "yaml", "csv", "table"}},
	{"PRICE_TIER", []string{"free", "pro", "enterprise", "trial"}},
	{"DEPLOY_STAGE", []string{"dev", "staging", "prod", "canary"}},
}

func (g *gen) configNames() []Row {
	var rows []Row
	for _, t := range configTerms {
		for _, v := range t.values {
			rows = append(rows, Row{Key: t.key, Value: v, Want: Open,
				Note: "the name and the value both describe configuration"})
		}
	}
	return rows
}

// -------------------------------------------------------- public prefixes

// publicPrefixes are values that a browser bundle already ships. Veiling one
// changes nothing about who can read it and only costs the agent information.
func (g *gen) publicPrefixes() []Row {
	prefixes := []string{"NEXT_PUBLIC_", "EXPO_PUBLIC_", "VITE_", "REACT_APP_", "PUBLIC_", "NUXT_PUBLIC_", "GATSBY_"}
	tails := []struct{ key, value string }{
		{"SITE_URL", "https://app.example.com"},
		{"API_URL", "https://api.example.com/v1"},
		{"SENTRY_DSN_PUBLIC", "https://o1.ingest.example.com/2"},
		{"GA_ID", "G-ABCD123456"},
		{"POSTHOG_HOST", "https://eu.posthog.com"},
		{"APP_NAME", "Checkout"},
		{"SUPPORT_EMAIL", "help@example.com"},
		{"MAPS_REGION", "AE"},
	}
	var rows []Row
	for _, p := range prefixes {
		for _, t := range tails {
			rows = append(rows, Row{Key: p + t.key, Value: t.value, Want: Open,
				Note: "a public bundle already ships this value"})
		}
	}
	return rows
}

// ------------------------------------------------------------ plain values

// plainValues are values that carry no credential under a name that says
// nothing. They guard the entropy rule against firing on ordinary text.
func (g *gen) plainValues() []Row {
	pairs := []struct{ key, value, note string }{
		{"WELCOME_MESSAGE", "Welcome to the application", "a sentence"},
		{"COMPANY_LEGAL_NAME", "ByteFinch Technologies SMC-Private Limited", "a company name"},
		{"SUPPORT_ADDRESS", "help@example.com", "an address a person reads"},
		{"BANNER_TEXT", "Scheduled maintenance on Sunday", "a sentence"},
		{"LONG_PRODUCT_IDENTIFIER", "projectidentifier1234567890", "a long readable identifier"},
		{"APPLICATION_TITLE", "myapplicationproductionv2", "a long readable identifier"},
		{"ORGANISATION_LABEL", "ThisIsAVeryLongCompanyNameHere", "a long readable identifier"},
		{"REPEATED_MARKER", "deadbeefdeadbeefdeadbeefdeadbeef", "hex with almost no information in it"},
		{"PADDING_VALUE", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "one character repeated"},
		{"COUNTER_SEQUENCE", "01234567890123456789012345678901", "digits in order"},
		{"CSV_COLUMNS", "id,name,email,created_at,updated_at", "a list a person reads"},
		{"CRON_SCHEDULE", "0 3 * * *", "a schedule"},
		{"USER_AGENT", "ByteFinch-Agent/1.0 (+https://bytefinch.dev)", "a user agent string"},
		{"ALLOWED_ORIGINS", "https://app.example.com,https://admin.example.com", "a list of origins"},
		{"CORS_METHODS", "GET,POST,PUT,DELETE,OPTIONS", "a list a person reads"},
		{"IP_ALLOWLIST", "10.0.0.0/8,192.168.0.0/16", "a list of networks"},
		{"NOTIFICATION_EMAILS", "ops@example.com,oncall@example.com", "a list of addresses"},
		{"DOCKER_IMAGE", "ghcr.io/bytefinch/app:1.4.2", "an image reference"},
		{"HELM_CHART", "oci://registry.example.com/charts/app", "a chart reference"},
		{"REPORTING_DB_URL", "postgres://appuser@db.internal:5432/appdb", "a url with no password in it"},
		{"CACHE_REDIS_URL", "redis://cache.internal:6379/0", "a url with no password in it"},
		{"BROKER_AMQP_URL", "amqp://rabbit.internal:5672/%2f", "a url with no password in it"},
		{"OTEL_EXPORTER_ENDPOINT", "http://otel-collector:4317", "a url with no password in it"},
		{"PROMETHEUS_SCRAPE_PATH", "/metrics", "a path"},
		{"STATIC_ASSET_PREFIX", "/static/v2", "a path"},
	}
	var rows []Row
	for _, p := range pairs {
		rows = append(rows, Row{Key: p.key, Value: p.value, Want: Open, Note: p.note})
	}
	return rows
}

// Counts reports how many rows of each label the corpus holds. The tests print
// it, so a change in the size of the set is visible in the log.
func Counts(rows []Row) map[Want]int {
	out := map[Want]int{}
	for _, r := range rows {
		out[r.Want]++
	}
	return out
}

// Keys returns every distinct variable name in the corpus, sorted.
func Keys(rows []Row) []string {
	seen := map[string]bool{}
	var out []string
	for _, r := range rows {
		if !seen[r.Key] {
			seen[r.Key] = true
			out = append(out, r.Key)
		}
	}
	sort.Strings(out)
	return out
}
